POST http://localhost:3001/api/exercises
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RVc2VybmFtZTIiLCJuYW1lIjoidGVzdE5hbWUyIiwiaWQiOiI2NjFlMmM2MGU2ZjJkMzk3M2Q5NmFmMzgiLCJpYXQiOjE3MTM5NDk3NDMsImV4cCI6MTcxMzk4NTc0M30.oTWCBSkwhqyHn-IrVqBTJTtnAlZwuMzwWCb7kMSvi0Q

{
  "name": "testuser1madethis"
}