POST http://localhost:3001/api/routines
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RVc2VybmFtZTMiLCJuYW1lIjoidGVzdE5hbWUzIiwiaWQiOiI2NjEyNmE5YjQzYTMwZGRkZmU2YzAzYWUiLCJpYXQiOjE3MTk0Njg2ODEsImV4cCI6MTcxOTUwNDY4MX0.BAEKB7HuQyfRRKuQLMgk3B0HFfqMTP7ehcEY6q1SgD8

{
  "name": "push day",
  "exercises": [
    {
      "exercise": "65f184021d517d70c13023e1"
    },
    {
      "exercise": "65f1840b1d517d70c13023e3",
      "repRange": "10-15"
    },
    {
      "exercise": "65f184171d517d70c13023e5",
      "repRange": "10-15"
    }
  ]
}