GET http://localhost:3001/api/routines?inactiveOnly
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RVc2VybmFtZTMiLCJuYW1lIjoidGVzdE5hbWUzIiwiaWQiOiI2NjEyNmE5YjQzYTMwZGRkZmU2YzAzYWUiLCJpYXQiOjE3MjQxNTEyODAsImV4cCI6MTcyNDE4NzI4MH0.f-5VPaeF6oE1oPbiCYa6QyH07dLDgjZT3riMfRXeRY4