GET http://localhost:3001/api/routines
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RVc2VybmFtZTMiLCJuYW1lIjoidGVzdE5hbWUzIiwiaWQiOiI2NjEyNmE5YjQzYTMwZGRkZmU2YzAzYWUiLCJpYXQiOjE3MTc0OTIwOTcsImV4cCI6MTcxNzUyODA5N30.Bxtju0OcLnDVEpYZnx6lJ-o7M49ymWnFb1dRAteBjEg