GET http://localhost:3001/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RVc2VybmFtZSIsIm5hbWUiOiJ0ZXN0TmFtZSIsImlkIjoiNjYwMjVjZjk1NGUxMGI0Njg1MWE2M2RmIiwiaWF0IjoxNzExNTIzNzQ0LCJleHAiOjE3MTE1MjM3NjR9.av9QXkwfQVeqOuyh9DTxZUvkrJ6vba2ET4RQM07yuK4