GET http://localhost:3001/api/workouts/660a61af6c92ae27e0c5a580?includeSets&includeExercises
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RVc2VybmFtZSIsIm5hbWUiOiJ0ZXN0TmFtZSIsImlkIjoiNjYwMjVjZjk1NGUxMGI0Njg1MWE2M2RmIiwiaWF0IjoxNzExOTU1NzI1LCJleHAiOjE3MTE5OTE3MjV9.0MHcPZHuJnh2S4B2UF8QRBPDiO2I1L9k1D57IxMh1gE