GET http://localhost:3001/api/exercises
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RVc2VybmFtZTMiLCJuYW1lIjoidGVzdE5hbWUzIiwiaWQiOiI2NjEyNmE5YjQzYTMwZGRkZmU2YzAzYWUiLCJpYXQiOjE3MTY5Njc3NTMsImV4cCI6MTcxNzAwMzc1M30.gYgB8na9THrU-8Ygoj4IGsnP0niuHBPqYLAkqu4To24