GET http://localhost:3001/api/routines/660559a0b48459427bae324f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RVc2VybmFtZTIiLCJuYW1lIjoidGVzdE5hbWUyIiwiaWQiOiI2NjA1NTY5MmZkNTA4M2FlNDM3MzcwOWYiLCJpYXQiOjE3MTE2MjU4ODYsImV4cCI6MTcxMTY2MTg4Nn0.QuuWdcz8yZQftmRGm0_1MuEycSfglnkA0QtZ46Eo1S4