POST http://localhost:3001/api/routines
Content-Type: application/json
Authorization: Bearer REPLACETHISWITHYOURAUTHORIZATIONTOKEN

{
  "name": "push day",
  "exercises": [
    {
      "exercise": "(exercise id goes here)",
      "repRange": "10-15",
      "amountOfSets": "3",
      "type": "regular"
    },
    {
      "exercise": "(exercise id goes here)",
      "repRange": "10-15",
      "amountOfSets": "3",
      "type": "regular"
    },
    {
      "exercise": "(exercise id goes here)",
      "repRange": "10-15",
      "amountOfSets": "3",
      "amountOfDropSets": "2",
      "type": "dropset"
    }
  ]
}